// FACT PROVENANCE. Every claim verified on 2026-07-14 against:
//   - WaveNet (the 2016 neural-TTS turning point) is a real, findable paper:
//     van den Oord et al., "WaveNet: A Generative Model for Raw Audio",
//     arXiv:1609.03499, https://arxiv.org/abs/1609.03499 (verified via web
//     search 2026-07-14; also published by DeepMind, Sept 2016). The article
//     cites it only for what it says: neural waveform generation that
//     substantially narrowed the gap to human-sounding speech, initially at
//     high computational cost.
//   - Pre-neural offline TTS being concatenative/formant-based is standard,
//     uncontroversial TTS history; described generically with no invented
//     numbers.
//   - LoudReader as the working example: voice models are BUNDLED in the app
//     and executed locally via Core ML with the Apple Neural Engine.
//     LoudReader/Engines/KokoroAneModelSeeder.swift (bundled model set,
//     `DownloadUtils.enforceOffline = true`, ANE model directory) and
//     LoudReader/Engines/KokoroAneSynthesisBackend.swift. The engine can
//     never download at runtime; that is enforced in code, not just policy.
//   - Apple Silicon requirement: components/money/site.ts REQUIREMENTS
//     ("iOS 18.0+, iPadOS 18.0+, macOS 15.0+ (Apple Silicon)").
//   - "8 natural offline voices" and English-only: components/money/site.ts
//     PRICING and existing money pages (consistent phrasing).
// Claims you may NOT make: any specific latency/RTF benchmark numbers, any
// claim that on-device quality has "matched" cloud quality (say "narrowed"),
// parameter counts of specific models (not published on this site).

import type { Faq } from "@/components/money/FaqSection";

export const FAQS: Faq[] = [
  {
    q: "How can a phone generate natural speech without the cloud?",
    a: "The same way the cloud does, at smaller scale. Natural-sounding speech comes from neural networks, and a neural network is just a large calculation that runs wherever the math can run. Modern phone and laptop chips include dedicated machine-learning hardware (Apple calls its version the Neural Engine), and researchers have built speech models compact enough to execute on it in real time. The audio is generated by your own processor, and no server is involved.",
  },
  {
    q: "Why were offline voices robotic for so long?",
    a: "Because before neural networks, offline synthesis worked by stitching together tiny recorded fragments or generating sound from hand-tuned rules. Both fit in small devices, and both sound mechanical, since the seams and flat prosody are audible. Neural text to speech (WaveNet in 2016 was the turning point) sounded dramatically more human but initially demanded datacenter hardware, so for years 'offline' and 'natural' were opposites. Efficient models and on-device ML accelerators ended that trade-off.",
  },
  {
    q: "What are the trade-offs of on-device TTS?",
    a: "Three honest ones. Size: the voice models must ship with the app or be downloaded once, so the app is bigger than a thin cloud client. Variety: a cloud service can host thousands of voices in dozens of languages, while an on-device app ships a curated set. LoudReader has 8 natural offline voices, English-only today. Hardware: you need a recent chip with ML acceleration. In exchange you get speech with zero network dependency and total privacy.",
  },
  {
    q: "Why does on-device TTS need Apple Silicon on a Mac?",
    a: "Neural speech synthesis is a heavy, continuous ML workload, and the model generates audio for hours at a time. Apple Silicon chips include a dedicated Neural Engine plus fast unified memory, which lets that workload run in real time without monopolizing the CPU. That's why LoudReader requires macOS 15+ on Apple Silicon. On older Intel Macs the honest alternative is the built-in Spoken Content feature.",
  },
  {
    q: "Is on-device voice quality catching up to cloud voices?",
    a: "Yes. The gap has narrowed dramatically, though it hasn't vanished. The best cloud voices are still ahead on expressiveness and sheer variety, because they can run enormous models. But compact neural models now produce speech that is natural enough to disappear into a book for hours, which is the bar that matters for reading. The honest way to judge is with your own ears: play a chapter offline and see.",
  },
];
