import Link from "next/link";

import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { APP_STORE_URL } from "@/components/money/site";

import { FAQS } from "./content";
import meta from "./meta.json";

export const metadata = articleMetadata(meta);

export default function OnDeviceTextToSpeechExplainedArticle() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr>
        <p>
          On-device text to speech means the voice you hear is generated by
          your own computer or phone. That speech step does not need to send
          text to a hosted speech service or receive audio from it. Older offline voices often sounded
          mechanical, but compact neural speech models and faster devices
          made natural local speech practical. Two changes helped: models
          became small enough to run locally,
          and chips like Apple Silicon shipped dedicated machine-learning
          hardware to run them on. Today an app like <strong>LoudReader</strong>{" "}
          generates natural offline voices on your device. Downloads, diagnostics and any connected services are separate things to check.
          This explainer covers how local speech works, why it
          took so long, and the trade-offs nobody should hide from you.
        </p>
      </Tldr>

      <ArticleIllustration
        variant="waveform"
        caption="Text in, waveform out, and the whole calculation happens on your own chip."
      />

      <QuestionSection question="What does &ldquo;on-device text to speech&rdquo; actually mean?">
        <p>
          Every text-to-speech system does the same job: it turns written
          words into an audio waveform that sounds like someone saying them.
          One architectural question is <em>where that computation runs</em>; model design and the surrounding application matter too.
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong className="text-gray-900">Cloud TTS:</strong> your text is
            uploaded to a server, a large model there generates audio, and the
            audio streams back. You need a connection, and your text, whatever
            it is, gets processed on hardware you don&apos;t control.
          </li>
          <li>
            <strong className="text-gray-900">On-device TTS:</strong> a
            compact model stored on your machine does the same generation
            locally. Once the required model is installed, this speech
            step does not need to upload the text or receive audio from a
            hosted speech service.
          </li>
        </ul>
        <p>
          This describes the speech step, not every feature of an app.
          Downloading a model, fetching a book, syncing files, or sending a
          message can still use a network. Check which steps process your
          content locally and which services receive it. We cover that
          distinction in{" "}
          <Link
            href="/private-text-to-speech-no-cloud"
            className="text-loudBlue hover:underline"
          >
            private text to speech with no cloud
          </Link>
          .
        </p>
      </QuestionSection>

      <QuestionSection question="Why were offline voices robotic for so long?">
        <p>
          Earlier systems often used recorded speech fragments or hand-tuned
          acoustic rules. Their joins and intonation could sound mechanical,
          although quality varied between systems. Local speech is not one
          fixed sound: it describes where generation happens, not a particular
          synthesis technique or a ceiling on quality.
        </p>
        <p>
          The turning point was neural speech synthesis. DeepMind&apos;s{" "}
          <a
            href="https://arxiv.org/abs/1609.03499"
            target="_blank"
            rel="noopener noreferrer"
            className="text-loudBlue hover:underline"
          >
            WaveNet paper (2016)
          </a>{" "}
          showed a neural network generating the raw audio waveform directly,
          and it substantially narrowed the gap to human-sounding speech. The
          catch was the computational cost of generating samples one at a
          time. Later models and faster hardware made neural speech easier to
          deploy on everyday devices. WaveNet is part of that history, not a
          benchmark for the voices in today&apos;s apps.
        </p>
      </QuestionSection>

      <QuestionSection question="How did neural voices move from the datacenter to your pocket?">
        <p>Two curves crossed, from opposite directions:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong className="text-gray-900">Models got smaller.</strong>{" "}
            Researchers spent the years after WaveNet making neural synthesis
            efficient. New architectures generate speech in far fewer steps,
            and compact open models now produce natural prosody at a fraction
            of the original computational cost.
          </li>
          <li>
            <strong className="text-gray-900">Devices got ML hardware.</strong>{" "}
            Phone and laptop processors can accelerate suitable models. On
            Apple platforms, Core ML offers CPU, GPU and Neural Engine
            options. The runtime and supported operations determine where the
            work runs; having an accelerator does not remove every bottleneck.
          </li>
        </ul>
        <p>
          A suitable model and runtime can generate speech without a remote
          server. LoudReader uses local speech for book narration. Other local
          tools, including Loudkit, download models during setup and then
          generate speech locally. Packaging varies by product and release;
          check resource availability before relying on disconnected use.
          Apple documents the runtime choices in its{" "}
          <a href="https://developer.apple.com/documentation/coreml/mlcomputeunits" className="text-loudBlue hover:underline">Core ML compute-unit guide</a>.
        </p>
      </QuestionSection>

      <ArticleIllustration
        variant="offline"
        caption="During local synthesis, the model turns text into audio on the device."
      />

      <QuestionSection question="What are the real trade-offs of on-device TTS?">
        <p>
          Honesty matters more than cheerleading here, because the trade-offs
          are real. They&apos;re just different from what people expect:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong className="text-gray-900">App size.</strong> The models
            have to live somewhere. They may come with the app or arrive in
            a separate download. Allow room for the model, generated audio,
            and later updates.
          </li>
          <li>
            <strong className="text-gray-900">Voice variety.</strong> A cloud
            service may offer a different voice and language selection from
            a local tool. LoudReader offers 23 studio narrators across 10
            languages, subject to device capability; Loudkit has its own 28-voice collection. Check the
            actual roster and samples rather than assuming the two products
            expose identical choices.
          </li>
          <li>
            <strong className="text-gray-900">Hardware floor.</strong> Real-time
            speech performance depends on the model and runtime. LoudReader
            requires iOS/iPadOS 18+ and can run its iPad build on compatible
            Apple Silicon Macs with macOS 15+. It has no separate native Mac
            build. Its requirements are not a rule for every local speech tool.
          </li>
        </ul>
        <p>
          Local synthesis avoids sending each passage to a hosted speech
          provider and keeps working without that provider&apos;s connection.
          Pricing, quotas, accounts, file sync and diagnostics are separate
          product decisions. LoudReader 1.12 also includes Sentry diagnostics
          and TelemetryDeck usage analytics, enabled by default; the privacy
          toggle is not exposed in that release. An on-device engine alone
          does not make an entire application network-free. See the{" "}
          <Link href="/privacy" className="text-loudBlue hover:underline">privacy policy</Link>.
        </p>
      </QuestionSection>

      <QuestionSection question="Is on-device quality catching up to the cloud?">
        <p>
          Where a model runs does not give it a quality score. Compare the
          voices on your own material: dialogue, unfamiliar names, numbers,
          and a longer passage. For reading, the useful question is whether
          you can follow a chapter comfortably. You can{" "}
          <a
            href={APP_STORE_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="text-loudBlue hover:underline"
          >
            install LoudReader
          </a>
          , prepare your chosen voice and book, disconnect and try a new passage. The Mac-specific picture,
          including what the built-in system voices can and can&apos;t do, is
          covered in{" "}
          <Link
            href="/offline-text-to-speech-mac"
            className="text-loudBlue hover:underline"
          >
            offline text to speech on Mac
          </Link>
          ; the iPhone side is in{" "}
          <Link
            href="/blog/text-to-speech-without-internet-iphone"
            className="text-loudBlue hover:underline"
          >
            text to speech without internet on iPhone
          </Link>
          .
        </p>
      </QuestionSection>

      <QuestionSection question="Should I use LoudReader, Loudkit, or Loudkit for agents?">
        <p>
          <strong>LoudReader</strong> is the app for listening to your books
          and documents. <a href="https://loudkit.loudreader.io/" className="text-loudBlue hover:underline">Loudkit</a>{" "}
          is the Apache-2.0 open-source speech framework for developers who
          want to add a voice to their own software. It provides SDKs and a
          command-line tool; you supply the application around it.
        </p>
        <p>
          <a href="https://loudkit.loudreader.io/agents/" className="text-loudBlue hover:underline">Loudkit for agents</a>{" "}
          is a separate developer preview for connecting local speech to an
          existing agent. Its current voice service needs an Apple Silicon
          Mac. Speech synthesis and transcription run locally after setup,
          while the agent&apos;s model and messenger can still use online
          services. The setup guide distinguishes tested speech providers
          from messenger delivery that still needs validation.
        </p>
      </QuestionSection>

      <FaqSection faqs={FAQS} />

      <StoreCta
        headline="Hear what on-device sounds like"
        subline="Try a book with a voice available on your device. Check the sound and workflow for yourself."
      />
    </ArticleLayout>
  );
}
