import Link from "next/link";

import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { APP_STORE_URL } from "@/components/money/site";

import { FAQS } from "./content";
import meta from "./meta.json";

export const metadata = articleMetadata(meta);

export default function OnDeviceTextToSpeechExplainedArticle() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr>
        <p>
          On-device text to speech means the voice you hear is generated by
          your own computer or phone. The text never travels to a server, and
          no server sends audio back. For most of TTS history that was a
          quality sacrifice, because natural-sounding speech needed datacenter
          hardware, so offline voices stayed robotic. Two things ended the
          trade-off: neural speech models became small enough to run locally,
          and chips like Apple Silicon shipped dedicated machine-learning
          hardware to run them on. Today an app like <strong>LoudReader</strong>{" "}
          generates natural offline voices entirely on a Mac or iPhone, which
          is why it can be fully on-device and private, your library never
          leaves your device. This explainer covers how that works, why it
          took so long, and the trade-offs nobody should hide from you.
        </p>
      </Tldr>

      <ArticleIllustration
        variant="waveform"
        caption="Text in, waveform out, and the whole calculation happens on your own chip."
      />

      <QuestionSection question="What does &ldquo;on-device text to speech&rdquo; actually mean?">
        <p>
          Every text-to-speech system does the same job: it turns written
          words into an audio waveform that sounds like someone saying them.
          The only architectural question is <em>where that computation runs</em>.
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong className="text-gray-900">Cloud TTS:</strong> your text is
            uploaded to a server, a large model there generates audio, and the
            audio streams back. You need a connection, and your text, whatever
            it is, gets processed on hardware you don&apos;t control.
          </li>
          <li>
            <strong className="text-gray-900">On-device TTS:</strong> a
            compact model stored on your machine does the same generation
            locally. Nothing is uploaded, nothing streams, and switching off
            Wi-Fi changes nothing.
          </li>
        </ul>
        <p>
          The distinction sounds technical but the consequences are practical:
          offline reliability, zero data cost, and privacy that is structural
          rather than promised. A cloud service protects your documents with a
          policy; an on-device app protects them with the absence of a server.
          That difference is the entire subject of{" "}
          <Link
            href="/private-text-to-speech-no-cloud"
            className="text-loudBlue hover:underline"
          >
            private text to speech with no cloud
          </Link>
          .
        </p>
      </QuestionSection>

      <QuestionSection question="Why were offline voices robotic for so long?">
        <p>
          Because the techniques that fit on a device were the ones that
          sounded mechanical. Classic offline synthesis either stitched
          together tiny fragments of recorded speech (concatenative synthesis)
          or generated sound from hand-tuned acoustic rules (formant
          synthesis). Both were small and fast; both produced the flat,
          seam-riddled voice everyone associates with &ldquo;computer
          reading.&rdquo;
        </p>
        <p>
          The turning point was neural speech synthesis. DeepMind&apos;s{" "}
          <a
            href="https://arxiv.org/abs/1609.03499"
            target="_blank"
            rel="noopener noreferrer"
            className="text-loudBlue hover:underline"
          >
            WaveNet paper (2016)
          </a>{" "}
          showed a neural network generating the raw audio waveform directly,
          and it substantially narrowed the gap to human-sounding speech. The
          catch: that first generation of neural TTS was computationally
          enormous. It lived in datacenters because nothing else could run it.
          So for years the market split, natural voices in the cloud and
          robotic voices on the device, and every reading app had to pick a
          side.
        </p>
      </QuestionSection>

      <QuestionSection question="How did neural voices move from the datacenter to your pocket?">
        <p>Two curves crossed, from opposite directions:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong className="text-gray-900">Models got smaller.</strong>{" "}
            Researchers spent the years after WaveNet making neural synthesis
            efficient. New architectures generate speech in far fewer steps,
            and compact open models now produce natural prosody at a fraction
            of the original computational cost.
          </li>
          <li>
            <strong className="text-gray-900">Devices got ML hardware.</strong>{" "}
            Phone and laptop chips stopped being general-purpose only. Apple
            Silicon ships a dedicated Neural Engine, silicon whose whole job
            is running neural networks, alongside fast unified memory that
            lets a model stream data without bottlenecks.
          </li>
        </ul>
        <p>
          When a small-enough model meets a fast-enough accelerator, the
          datacenter stops being necessary. LoudReader is a concrete example of
          the pattern: its voice models ship inside the app, execute on the
          Neural Engine via Core ML, and the engine is written so it{" "}
          <em>cannot</em> download anything at runtime. Offline isn&apos;t a
          mode here, it&apos;s the architecture. That&apos;s what &ldquo;natural
          offline voices&rdquo; means mechanically: a neural model that once
          needed a server rack, running quietly on the chip you already own.
        </p>
      </QuestionSection>

      <ArticleIllustration
        variant="offline"
        caption="No server round-trip. The model, the text, and the audio all stay on the device."
      />

      <QuestionSection question="What are the real trade-offs of on-device TTS?">
        <p>
          Honesty matters more than cheerleading here, because the trade-offs
          are real. They&apos;re just different from what people expect:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong className="text-gray-900">App size.</strong> The models
            have to live somewhere. An on-device app ships its voices inside
            the download, so it&apos;s heavier than a thin cloud client. You
            pay in storage once instead of in bandwidth forever.
          </li>
          <li>
            <strong className="text-gray-900">Voice variety.</strong> A cloud
            service can host thousands of voices in dozens of languages
            because they all live server-side. An on-device app ships a
            curated set. LoudReader offers 23 natural offline narrators
            across 10 languages. If you need Mandarin or a celebrity
            soundalike, the cloud genuinely serves you better.
          </li>
          <li>
            <strong className="text-gray-900">Hardware floor.</strong> Real-time
            neural synthesis needs a modern chip. LoudReader requires macOS
            15+ on Apple Silicon, or iOS 18+ on iPhone. An Intel Mac
            can&apos;t run it, and pretending otherwise would help nobody.
          </li>
        </ul>
        <p>
          What you get in exchange: no word quotas metered by a server, no
          subscription tied to compute costs someone else is paying, no outage
          that takes your reading with it, and no copy of your documents
          anywhere but your own disk.
        </p>
      </QuestionSection>

      <QuestionSection question="Is on-device quality catching up to the cloud?">
        <p>
          The gap has narrowed dramatically, and it keeps narrowing, but the
          honest answer is that the largest cloud models are still ahead on
          expressiveness and variety, because scale still buys something. The
          more useful question for a reader is whether an on-device voice is
          natural enough to disappear into a book for three hours. That bar
          has been cleared, and it&apos;s a claim you can test in minutes
          without trusting anyone:{" "}
          <a
            href={APP_STORE_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="text-loudBlue hover:underline"
          >
            install LoudReader
          </a>
          , switch off Wi-Fi, and play a chapter. The Mac-specific picture,
          including what the built-in system voices can and can&apos;t do, is
          covered in{" "}
          <Link
            href="/offline-text-to-speech-mac"
            className="text-loudBlue hover:underline"
          >
            offline text to speech on Mac
          </Link>
          ; the iPhone side is in{" "}
          <Link
            href="/blog/text-to-speech-without-internet-iphone"
            className="text-loudBlue hover:underline"
          >
            text to speech without internet on iPhone
          </Link>
          .
        </p>
      </QuestionSection>

      <FaqSection faqs={FAQS} />

      <StoreCta
        headline="Hear what on-device sounds like"
        subline="Natural offline voices, generated on your Mac or iPhone. Free, no account. Turn off Wi-Fi and judge for yourself."
      />
    </ArticleLayout>
  );
}
