import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FREE_TIER } from "@/components/money/site";
import { FAQS } from "./content";
import meta from "./meta.json";
export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>For a first English book, a short complete story is often a more manageable commitment than a famous long novel. Start by sampling <em>The Tale of Peter Rabbit</em>, an individual Aesop fable or a chapter of <em>The Wonderful Wizard of Oz</em>. The eight choices below range from short starting points to longer stretches. They are editorial suggestions, not CEFR grades, and “children’s classic” does not mean every word is easy. Each links to a specific Project Gutenberg edition. Read a page, try its narration if useful and choose based on whether you can follow the story.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Sample a short story before committing to a long novel." />
<QuestionSection question="Which books are worth sampling first?"><ul className="list-disc pl-6 space-y-2"><li><strong><a href="https://www.gutenberg.org/ebooks/14838" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">The Tale of Peter Rabbit — Beatrix Potter</a>.</strong> A short, self-contained starting point. The illustrations provide context if you use them, but garden vocabulary and unfamiliar names may still need checking. Read the whole story before deciding you need a longer book.</li><li><strong><a href="https://www.gutenberg.org/ebooks/21" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">Three Hundred Aesop’s Fables — translated by George Fyler Townsend</a>.</strong> Choose one fable at a time rather than committing to the collection. Short length is useful, but this translation includes older phrasing. If the moral is unclear, restate the events before trying to interpret it.</li><li><strong><a href="https://www.gutenberg.org/ebooks/55" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">The Wonderful Wizard of Oz — L. Frank Baum</a>.</strong> A possible first longer story when you want a clear journey to follow. Sample a chapter to judge the descriptions and unfamiliar creatures; recognising a film plot does not guarantee that all of the book will be familiar.</li><li><strong><a href="https://www.gutenberg.org/ebooks/11" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">Alice’s Adventures in Wonderland — Lewis Carroll</a>.</strong> An option if you enjoy playful language. It is not the default beginner recommendation: jokes, invented words and shifts in logic can be difficult even when the sentences look short.</li></ul><p>These are alternatives, not compulsory steps. If none feels comfortable, a modern graded reader may give you a better match to your current vocabulary.</p></QuestionSection>
<QuestionSection question="What can you try when you want a longer challenge?"><ul className="list-disc pl-6 space-y-2"><li><strong><a href="https://www.gutenberg.org/ebooks/271" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">Black Beauty — Anna Sewell</a>.</strong> Try it if first-person narration helps you stay with a story. Expect historical vocabulary about horses and work, and episodes involving cruelty; a gentle title does not mean a gentle story throughout.</li><li><strong><a href="https://www.gutenberg.org/ebooks/215" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">The Call of the Wild — Jack London</a>.</strong> A choice for readers interested in an adventure setting. Nature and survival vocabulary make it a stretch rather than a universal easy pick. It also contains violence and animal suffering.</li><li><strong><a href="https://www.gutenberg.org/ebooks/1661" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">The Adventures of Sherlock Holmes — Arthur Conan Doyle</a>.</strong> The individual mysteries offer stopping points without reading the full collection. Victorian expressions and details important to the solution reward careful checking. Choose one story and see whether you can explain the case.</li><li><strong><a href="https://www.gutenberg.org/ebooks/45" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">Anne of Green Gables — L. M. Montgomery</a>.</strong> Consider it when you want a longer, character-focused novel. Dialogue, descriptive passages and Anne’s imaginative language create different challenges from a short fable.</li></ul><p>Older books can also contain social attitudes and language that need historical context. Choose according to your interest and comfort as well as sentence difficulty.</p></QuestionSection>
<QuestionSection question="Are the linked editions free everywhere?"><p>Project Gutenberg lists these editions as public domain in the United States. Its <a href="https://www.gutenberg.org/policy/permission.html" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">permissions guidance</a> asks readers elsewhere to check local copyright. A different translation, introduction or illustrated edition may have different rights. The links identify the editions being discussed, not a worldwide permission for every version of each title.</p></QuestionSection>
<QuestionSection question="How do you choose without a reading-level score?"><p>Read a page from the opening and another from later in the book. Then describe the situation without looking. If unfamiliar words prevent you from explaining it, try another title or an adapted edition. You do not need to understand every joke or decorative detail, but you should know what is happening.</p><p>For a lookup strategy, see <Link href="/blog/reading-english-books-non-native" className="text-loudBlue hover:underline">reading English books as a non-native speaker</Link>. Use your understanding of the sample rather than treating the order of this list as a formal grading scale.</p></QuestionSection>
<QuestionSection question="How can you listen to your chosen book?"><p><Link href="/" className="text-loudBlue hover:underline">LoudReader</Link> includes browsing and downloading from Project Gutenberg, or you can import a supported DRM-free EPUB. Press play and use word highlighting to follow the passage; pause and replay sentences when needed. Synthetic narration can make pronunciation mistakes, so check unfamiliar names or doubtful words against another source.</p><p>{FREE_TIER.full} Adjustable playback speed is Premium. The app runs on iPhone and iPad, with its iPad build available on compatible Apple Silicon Macs. Prepare the book and voice assets before relying on offline playback.</p><p>We do not give fixed completion times here: edition length, voice, speed and pauses all change them. Plan for a short session and use the end of a story or chapter as a stopping point. The <Link href="/blog/learn-english-by-listening-to-books" className="text-loudBlue hover:underline">English listening routine</Link> gives a way to turn those sessions into practice.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Try your first English chapter" subline="Browse the catalogue or import a supported EPUB, then follow narration with word highlighting." />
    </ArticleLayout>
  );
}
