import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FREE_TIER } from "@/components/money/site";
import { FAQS } from "./content";
import meta from "./meta.json";
export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>If you have ADHD and keep losing your place in a book, narration is one reading format worth trying. A moving highlight shows where the voice is speaking, and pausing or replaying a sentence gives you a way back into the passage. Those are useful controls, not evidence that an app treats ADHD or guarantees concentration. Sound can also become another distraction. Start with a manageable passage, compare it with your usual reading method and judge whether you can follow the meaning. This guide explains what to change, what to notice and where <Link href="/" className="text-loudBlue hover:underline">LoudReader</Link> fits.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Use the highlight as a location cue, and pause when you need to return to the meaning." />
<QuestionSection question="What difficulty are you trying to solve?"><p>Losing your place, avoiding a long chapter and understanding a dense argument are different problems. Before changing tools, describe the one that happens most often. For example: “I can read each sentence but forget how it connects to the last,” or “I keep searching for the line after an interruption.” That gives you something concrete to assess.</p><p>The <a href="https://www.nhs.uk/conditions/adhd-adults/" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">NHS overview of adult ADHD</a> describes attention and organisation difficulties and the importance of individual support. It does not establish a TTS treatment effect. This article offers a reading experiment, not a medical explanation for every difficulty with text.</p></QuestionSection>
<QuestionSection question="What can narration and highlighting change?"><ul className="list-disc pl-6 space-y-2"><li><strong>A visible location.</strong> Word highlighting indicates the current narration position. You can return to that location after pausing; if you missed the meaning, replay the passage too.</li><li><strong>An adjustable pace.</strong> Audio advances through the text until you pause it. This may feel useful or rushed. There is no need to keep up when you need time to think.</li><li><strong>A different way to read.</strong> You can listen without holding the book open when the material does not require figures or close annotation.</li><li><strong>More input.</strong> Hearing and seeing words together can also feel busy. You can switch back to text alone, or try audio alone with a familiar passage.</li></ul><p>None of these controls guarantees comprehension. A highlight tells you where the reader is speaking, not whether you understood the preceding paragraph.</p></QuestionSection>
<QuestionSection question="How can you try it without turning setup into another task?"><ol className="list-decimal pl-6 space-y-2"><li>Choose a short passage you actually need or want to read. Keep your usual reading option available.</li><li>Use the default voice and normal speed first. Avoid changing several settings at once.</li><li>Read with narration for a manageable stretch, then pause. Say or write the main point without looking.</li><li>Notice the practical friction: did you lose your place, miss the content, dislike the voice or feel hurried?</li><li>Change one thing for the next section: a quieter setting, a different voice, a smaller passage or reading without audio.</li><li>Try again on another day or another kind of text before deciding the format is useful or useless.</li></ol><p>This is a personal usability check, not a clinical test. One good or frustrating chapter is information about that session, not a verdict about your attention.</p></QuestionSection>
<QuestionSection question="Which playback speed should you use?"><p>Start where the words are comfortable to follow. If the narration seems hurried, pause or use a slower pace. If it feels unnecessarily slow on familiar material, try a small increase and check your understanding. There is no verified “ADHD speed” recommended here, and faster is not inherently better.</p><p>LoudReader Premium offers 0.3x to 3.0x speed control. Normal-speed playback, word highlighting, sentence replay, notes and highlights are available without making speed adjustment essential to the workflow. {FREE_TIER.full}</p></QuestionSection>
<QuestionSection question="Can you listen while moving?"><p>LoudReader supports background playback and lock-screen media controls. After the book and needed voice assets are available, narration can continue without a connection. This makes audio an option while folding laundry or taking a familiar walk, if you can still attend to the activity safely.</p><p>Try familiar or lighter material first. If the task and the book compete for your attention, save the passage for a seated session. For dense study, keep figures and the source text accessible rather than trying to understand everything while doing something else.</p></QuestionSection>
<QuestionSection question="What should you know before using LoudReader?"><p>It is an iPhone and iPad reading app; the iPad build can run on compatible Apple Silicon Macs. It reads supported DRM-free EPUBs and PDFs, with local speech generation. Import quality still matters: OCR or a complicated page layout can introduce errors that have nothing to do with your attention.</p><p>For coursework, <Link href="/blog/text-to-speech-for-students" className="text-loudBlue hover:underline">the student workflow</Link> covers file checks and note-taking. If reading difficulties are affecting studies or everyday life, the NHS guide above describes routes to support; a reading app can be one tool alongside that support.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Try a manageable passage" subline="Word highlighting, sentence replay and local narration. Choose the format that helps you follow the text." />
    </ArticleLayout>
  );
}
