import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FREE_TIER } from "@/components/money/site";
import { FAQS } from "./content";
import meta from "./meta.json";
export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>Text to speech can make a chapter or your own notes easier to revisit. Whether that becomes useful study depends on what you do next: pause, explain the idea without the text, and check your answer. Listening time by itself is not evidence that you have learned the material. Reading along can help you locate a passage, but hearing and seeing the same words does not guarantee better memory. This guide separates useful study tasks from situations where audio needs support. <Link href="/" className="text-loudBlue hover:underline">LoudReader</Link> can supply the narration for supported EPUBs and PDFs; it does not grade your understanding or replace a problem set.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Read, listen, pause and return to the passage you need." />
<QuestionSection question="What does the research actually support?"><p>An often-repeated claim says reading while listening automatically creates two stronger memories. That is too simple a justification for choosing a study tool. The practical question is whether you can explain or use the material afterwards.</p><p>A relevant <a href="https://journals.sagepub.com/doi/10.1111/j.1467-9280.2006.01693.x" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">2006 study by Roediger and Karpicke</a> compared recalling prose passages with studying them again. Recall practice led to better retention on delayed tests, although repeated study did better on an immediate test. It did not test LoudReader or establish that TTS improves grades. It supports adding a memory check after a passage instead of judging a session by how familiar the words feel.</p></QuestionSection>
<QuestionSection question="Which study tasks suit listening?"><ul className="list-disc pl-6 space-y-2"><li><strong>Preview a prose chapter.</strong> Listen to an introduction to identify its question and structure, then decide what needs close reading.</li><li><strong>Revisit your own notes.</strong> Turn a summary into a short listening session. Pause at a heading and predict the next point before playing it.</li><li><strong>Read an assigned story.</strong> Keep the text available for quotations and page references. Narration can provide another way through a long reading assignment.</li><li><strong>Check writing by ear.</strong> Listen for missing words, repeated phrases or a sentence that becomes hard to follow. Verify suspected errors in the original.</li></ul><p>These are possible uses, not a ranking of study methods for every student. If the voice adds distraction, silent reading remains a useful option.</p></QuestionSection>
<QuestionSection question="What should stay in front of you?"><p>Keep diagrams, charts, equations and code visible. A voice reading nearby prose cannot tell you everything represented by a graph, and a PDF may extract columns or footnotes in the wrong order. Listen to a short sample before treating its audio as reliable.</p><p>For a derivation, pause and work the next step yourself. For a historical argument, write its claim and the evidence. For vocabulary, try producing the meaning before looking. Match the activity to the skill the course expects you to demonstrate.</p></QuestionSection>
<QuestionSection question="What does a useful twenty-minute session look like?"><ol className="list-decimal pl-6 space-y-2"><li>Choose one small section and write a question you want it to answer.</li><li>Read or listen for a few minutes. Keep the source open when figures or unfamiliar terms matter.</li><li>Pause and close or cover the text. Explain the main point in your own words, or attempt a relevant practice question.</li><li>Check your answer against the source. Mark the specific gap rather than replaying an entire chapter automatically.</li><li>Return to that question in a later session and see what you can still produce.</li></ol><p>Twenty minutes is a convenient example, not a scientifically optimal duration. Shorten it or take a break if you are no longer following the argument.</p></QuestionSection>
<QuestionSection question="How does LoudReader fit into that routine?"><p>Import a supported DRM-free EPUB or PDF, then check the first page of extracted text. The current app can apply local OCR to scanned PDFs, but recognition and reading order still need checking, especially with formulas or several columns. The <Link href="/turn-any-book-into-an-audiobook" className="text-loudBlue hover:underline">book-to-audio guide</Link> covers the import flow.</p><p>Word highlighting and sentence replay help you return to a passage. Notes and highlights are included; Premium adds speed control from 0.3x to 3.0x. {FREE_TIER.full} Choose a pace at which you can explain what you just heard; faster playback is not a study target.</p><p>Narration is generated on the device after the required downloads. LoudReader runs on iPhone and iPad, with the iPad build available on compatible Apple Silicon Macs. For organising a whole reading list, see <Link href="/blog/text-to-speech-for-students" className="text-loudBlue hover:underline">the student workflow guide</Link>.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Try a chapter in LoudReader" subline="Local narration and word highlighting. All voices free for the first 8 listening hours." />
    </ArticleLayout>
  );
}
