import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FREE_TIER } from "@/components/money/site";
import { FAQS } from "./content";
import meta from "./meta.json";
export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>Books can supply material for English listening practice, especially when the text is available to check an unfamiliar phrase. You do not have to read along at all times, and reading with audio is not proven to beat every other approach. Start with material you can mostly follow, try a short passage with the text, then decide what needs another listen or a dictionary check. <Link href="/" className="text-loudBlue hover:underline">LoudReader</Link> provides narration and word highlighting for supported books; the learning work is noticing, checking and using the language. This guide focuses on building that routine over time, not on promises of fluency from passive listening.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Keep the text available to check what you heard, and revisit a few useful phrases." />
<QuestionSection question="What does research on listening to stories tell us?"><p>In <a href="https://nflrc.hawaii.edu/rfl/item-detail/174" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">Brown, Waring and Donkaewbua’s 2008 study</a>, 35 Japanese university learners encountered vocabulary through reading, reading while listening and listening alone. Reading with audio did not significantly outperform reading alone on the vocabulary tests; most target words were not learned. The study used graded stories, not LoudReader or synthetic voices.</p><p>That is a reason for modest expectations. A story is useful language practice, but hearing a new word once is not a reliable vocabulary lesson. Use the format that lets you follow the passage, and deliberately revisit a few words that matter to you.</p></QuestionSection>
<QuestionSection question="Should you keep the text visible?"><p>Try it when you are unsure which words you heard or how a phrase is spelt. The text lets you distinguish an unfamiliar word from familiar words running together. A moving highlight can make the narration position easier to find, but you can pause whenever the pace is unhelpful.</p><p>For a familiar passage, try listening with the text hidden, then reveal it to check the parts you missed. This is a practical way to identify a problem, not a rule that everyone must graduate from text to audio. Reading alone is still worthwhile language practice.</p></QuestionSection>
<QuestionSection question="How do you choose material you will actually finish?"><p>Begin with a page or a complete short story, not a commitment to a long novel. After a sample, describe what happened. If you need a dictionary for nearly every sentence, choose a simpler text or a graded reader designed for your level.</p><p>Familiar plots can reduce the amount of new context you need to follow. Older children’s classics are available from Project Gutenberg, but children’s literature is not automatically beginner English: wordplay, historical phrasing and dialect can be difficult. The <Link href="/blog/easy-english-books-to-listen-to" className="text-loudBlue hover:underline">book shortlist</Link> explains those trade-offs and links specific editions.</p><p>A modern book you want to read may be a better choice than a classic you dislike. Use a compatible DRM-free edition you are entitled to import.</p></QuestionSection>
<QuestionSection question="What does a repeatable practice session look like?"><ol className="list-decimal pl-6 space-y-2"><li>Choose a short passage and a task: follow the plot, identify unfamiliar phrases or practise listening without the text.</li><li>Read or listen once without interrupting every sentence. Pause when you lose the meaning, not simply whenever you see a new word.</li><li>Select a few useful unknown words or phrases. Check their meanings and, when necessary, a dictionary pronunciation.</li><li>Replay the passage and see whether it is easier to follow. Try explaining it in English or using one phrase in your own sentence.</li><li>At the next session, briefly revisit those phrases before moving on. Keep the amount small enough that practice remains manageable.</li></ol><p>Ten or twenty minutes is a convenient starting plan, not a tested prescription. Adjust it to the material and your available attention. Finishing every page is less useful than noticing when you have stopped following it.</p></QuestionSection>
<QuestionSection question="How should you use speed and synthetic pronunciation?"><p>Start at a comfortable pace. If you need more time, pause between sentences or try a slower setting; extreme slowing can make phrasing less representative of conversation. Return to the original pace occasionally if your aim is to recognise speech at that pace.</p><p>Synthetic speech can mispronounce names, abbreviations or words whose pronunciation depends on context. For a pronunciation question, compare it with a dictionary recording, a teacher or suitable human speech. A narrator is a practice source, not an authority on every accent.</p><p>LoudReader Premium offers 0.3x to 3.0x playback speed. Normal-speed reading, word highlighting, sentence replay, notes and highlights can support a routine without Premium speed control.</p></QuestionSection>
<QuestionSection question="What does LoudReader contribute?"><p>It narrates supported DRM-free EPUBs and PDFs and includes access to a downloadable Project Gutenberg catalogue. Speech runs locally after required resources are available, so a prepared book can be used offline. The app runs on iPhone and iPad, with its iPad build available on compatible Apple Silicon Macs.</p><p>{FREE_TIER.full} Voice availability depends on the device. Choose based on your own passage, and keep another pronunciation source available when accuracy matters. For a focused exercise rather than a reading habit, see <Link href="/blog/text-to-speech-for-esl-learners" className="text-loudBlue hover:underline">TTS exercises for English learners</Link>.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Build a reading-and-listening routine" subline="Choose a manageable book, check the voice on your own text and practise at your pace." />
    </ArticleLayout>
  );
}
