// FACT PROVENANCE. Verified on 2026-07-14:
//   - The article deliberately makes NO claims about any specific
//     competitor's retention, training, or data practices. Every statement
//     about cloud TTS is architectural/definitional (server-side synthesis
//     requires transmitting the text to the server) or is framed as "what a
//     privacy policy governs / what to check", not as an accusation. This
//     keeps the page accurate without day-of-writing policy audits.
//   - App Store privacy labels ("App Privacy" section on every listing) are
//     a real, verifiable Apple feature (apps declare data collection;
//     visible on any App Store product page).
//   - Airplane-mode test phrasing is consistent with the vetted money page
//     app/(seo)/private-text-to-speech-no-cloud/.
//   - LoudReader claims, verified against the app source (LoudReader_mac
//     repo, main branch) and shared site facts:
//       - on-device synthesis, works offline: TTS engines run locally
//         (CoreML/ONNX in-app); consistent with the airplane-mode claim on
//         the private-TTS money page.
//       - no account / no sign-up: components/money/site.ts PRICING and the
//         private-TTS money page ("no sign-up, no login, no profile").
//       - imported files are stored in the app's local container:
//         BookImportService.swift (FileManager .documentDirectory).
//       - the only network requests are downloads the user asks for
//         (Gutenberg catalog, pasted article links): consistent with the
//         vetted "minimal network surface" claim on the private-TTS page;
//         Gutenberg fetches via ProjectGutenbergService.swift.
//   - Honest concessions included: on-device trade-offs (fewer voices,
//     English-only today, modern-hardware requirement) from the private-TTS
//     money page and site.ts REQUIREMENTS.
// Claims you may NOT make: that any named app retains/trains on user
// documents (unverified per-vendor), malware statistics, breach statistics.
// No studies are cited in this article.

import type { Faq } from "@/components/money/FaqSection";

export const FAQS: Faq[] = [
  {
    q: "Does a text-to-speech app upload my document to a server?",
    a: "It depends entirely on where the voice is generated. Cloud TTS apps synthesize speech on the provider's servers, so the text you listen to has to be transmitted to them. That is the architecture, not a hidden behavior. On-device TTS apps generate the voice on your own hardware, so the document never needs to leave your device.",
  },
  {
    q: "How can I tell if a TTS app processes text in the cloud?",
    a: "The airplane-mode test is the fastest check: turn off all connectivity and press play. An app that keeps narrating is synthesizing speech on the device; an app that stops, errors, or falls back to a robotic voice is calling a server. Other signs of cloud processing: the app requires an account, meters you by words per month, or its App Store privacy label lists collected content.",
  },
  {
    q: "What should I look for in a TTS app's privacy policy?",
    a: "Five things: what content is collected (documents, text, audio); how long it is retained; which third parties or subprocessors receive it; whether your content can be used to train models; and how deletion works. If the policy is silent on any of these for the text you upload, assume the least favorable answer until the vendor says otherwise.",
  },
  {
    q: "What does on-device text to speech mean?",
    a: "The speech is generated by a model running on your own device's processor, not on a server. Nothing is transmitted to be synthesized, which is why it works in airplane mode, and privacy stops depending on a vendor's terms. There is no server-side copy of your reading because there is no server involved at all.",
  },
  {
    q: "Does LoudReader ever see what I read?",
    a: "No. LoudReader is fully on-device and private, your library never leaves your device. There is no account, imported books and documents are stored locally on your device, and speech is generated on the device itself. The only network requests are downloads you explicitly ask for, like fetching a free classic from the built-in Project Gutenberg catalog.",
  },
];
