import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FREE_TIER } from "@/components/money/site";
import { FAQS } from "./content";
import meta from "./meta.json";
export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>Text to speech can turn suitable book text into audio, but choosing an accessible reading setup involves more than voice quality. You also need to find a file, import it, start playback and return to the right place. <Link href="/" className="text-loudBlue hover:underline">LoudReader</Link> is a book and document reader, not a system screen reader. We have not verified its complete import-to-playback workflow with VoiceOver, so this guide does not promise independent operation for every reader. It explains what to test before relying on the app, how it differs from built-in accessibility tools and which file problems can affect narration.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Assess the whole reading workflow, from finding a book to returning to a passage." />
<QuestionSection question="How is a book reader different from VoiceOver?"><p><a href="https://support.apple.com/en-gb/guide/iphone/iph3e2e415f/ios" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">Apple’s VoiceOver guide</a> describes using spoken feedback and gestures to navigate iPhone. A document reader focuses on the content of a book or article. VoiceOver can also read content; you do not necessarily need a separate app to listen to a novel.</p><p>Apple also provides <a href="https://support.apple.com/en-gb/guide/iphone/iph96b214f0/ios" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">Read &amp; Speak controls</a> for spoken content. Start with the tools you already use. Consider a separate reader when its library, narration or position controls solve a particular problem, and assess the whole workflow before paying.</p></QuestionSection>
<QuestionSection question="What should you test in a reading app?"><ul className="list-disc pl-6 space-y-2"><li><strong>Finding a book.</strong> Can you identify and open the title you want with your normal accessibility settings?</li><li><strong>Importing a document.</strong> Can you complete the file-picker or share-sheet flow and recognise whether import succeeded?</li><li><strong>Starting and stopping.</strong> Can you locate play and pause, choose a voice and understand the state of playback?</li><li><strong>Returning to a passage.</strong> Can you move back after an interruption and resume at a useful location?</li><li><strong>Handling a problem.</strong> Is an unsupported or failed import explained in a way you can access?</li><li><strong>Reading with your display settings.</strong> If you use visible text, test the actual font size, contrast and magnification settings you rely on.</li></ul><p>Try these with one familiar short document. The test is whether they work with your device and interaction method, not whether an app description calls the interface simple.</p></QuestionSection>
<QuestionSection question="Which documents can LoudReader narrate?"><p>It imports DRM-free EPUB and PDF files. Do not assume a purchased ebook is exportable; check whether the seller supplies a compatible file. The app also offers a Project Gutenberg catalogue, with downloads subject to local copyright rules. Availability on one device does not automatically copy a library to another.</p><p>Text-based PDFs can have reading-order issues in columns, tables and footnotes. The current app includes local text recognition for scanned PDFs, but OCR may misread poor scans or omit information. Images and diagrams do not become full descriptions merely because surrounding text can be spoken.</p><p>If important content is inaccessible, ask its provider for an accessible edition or an alternative format. The <Link href="/turn-any-book-into-an-audiobook" className="text-loudBlue hover:underline">import guide</Link> describes the supported book workflow.</p></QuestionSection>
<QuestionSection question="What is verified about LoudReader’s listening controls?"><p>The app supports narration with the screen locked and system media controls for playback. It remembers a reading position within the app. Word-following highlighting indicates the spoken location for readers who can use it, and notes and highlights are available on the free tier.</p><p>These features do not establish complete VoiceOver compatibility. We have not run an end-to-end accessibility test of selecting a book, importing it, choosing a voice and recovering from an error. If a control is inaccessible in your setup, treat that as a limitation of the app, not something you should have to work around.</p></QuestionSection>
<QuestionSection question="How should you choose a voice and speed?"><p>Use a passage with ordinary prose, names and punctuation from the kind of material you read. Check whether words remain clear over several paragraphs and whether unexpected pronunciation interrupts the meaning. A brief polished sample is useful, but your own document is a better fit check.</p><p>LoudReader advertises 23 studio narrators across 10 languages, with availability depending on the device. {FREE_TIER.full} Premium keeps the full available selection and adds speed control from 0.3x to 3.0x. Try normal speed first; use a pace that is comfortable for the material rather than a target number.</p></QuestionSection>
<QuestionSection question="What about offline use and different devices?"><p>Speech generation and scanned-PDF text recognition happen locally. Make the book and required voice resources available, then check the desired setup before depending on it without a connection. Local narration is not a promise that the entire app has no networking or diagnostics.</p><p>LoudReader is an iPhone and iPad app. Compatible Apple Silicon Macs can run its iPad build; it is not a separate native Mac app, and it does not automatically sync libraries or positions between devices. See the <Link href="/faq" className="text-loudBlue hover:underline">product FAQ</Link> for current platform and feature details.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Check your own reading setup" subline="Try a familiar document and the controls you rely on before choosing a reader." />
    </ArticleLayout>
  );
}
