import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FAQS } from "./content";
import meta from "./meta.json";

export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>Choose your next listen by the kind of session you want: a few poems, a short complete story, separate detective cases or a novel to return to over weeks. The shortlist below points to specific Gutenberg editions and our corresponding reading pages. Durations are catalogue estimates at normal speed, not measured recordings; voice, pace, edition and pauses change them. Gutenberg’s US public-domain designation does not settle the status of an edition in every country. Check the source notice and your local position before downloading.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Choose a session length, then sample the specific edition." />
      <QuestionSection question="What fits a short listening session?"><p>Elizabeth Barrett Browning’s <Link href="/listen/sonnets-from-the-portuguese" className="text-loudBlue hover:underline">Sonnets from the Portuguese</Link> is a collection you can approach a poem at a time. Our catalogue estimates roughly an hour for the whole work, but there is no need to hear it in one sitting. <a href="https://www.gutenberg.org/ebooks/2002" className="text-loudBlue hover:underline">Gutenberg edition 2002</a> identifies the source edition.</p><p>Poetry is a useful reminder that shorter does not mean less demanding. Try one poem with the text visible, then decide whether you want to continue with that voice. TTS may not pause where you would when reading verse yourself.</p></QuestionSection>
      <QuestionSection question="What if you want a short continuous story?"><p>Lewis Carroll’s <Link href="/listen/alices-adventures-in-wonderland" className="text-loudBlue hover:underline">Alice’s Adventures in Wonderland</Link> and Robert Louis Stevenson’s <Link href="/listen/the-strange-case-of-dr-jekyll-and-mr-hyde" className="text-loudBlue hover:underline">The Strange Case of Dr Jekyll and Mr Hyde</Link> each have catalogue estimates of about three hours. The first offers wordplay and strange encounters; the second offers a compact mystery with a darker atmosphere.</p><p>Check the source pages for <a href="https://www.gutenberg.org/ebooks/11" className="text-loudBlue hover:underline">Alice, edition 11</a> and <a href="https://www.gutenberg.org/ebooks/43" className="text-loudBlue hover:underline">Jekyll and Hyde, edition 43</a>. Sample dialogue and unfamiliar words before making either your first long TTS session.</p></QuestionSection>
      <QuestionSection question="What suits listening in separate pieces?"><p>Arthur Conan Doyle’s <Link href="/listen/the-adventures-of-sherlock-holmes" className="text-loudBlue hover:underline">The Adventures of Sherlock Holmes</Link> is organised as separate cases, so you can choose a story rather than commit to the whole collection. The <a href="https://www.gutenberg.org/ebooks/1661" className="text-loudBlue hover:underline">Gutenberg contents list</a> lets you see those divisions before downloading.</p><p>For a longer continuous mystery, consider Wilkie Collins’s <Link href="/listen/the-moonstone" className="text-loudBlue hover:underline">The Moonstone</Link>. Its catalogue estimate is around twenty-one hours. <a href="https://www.gutenberg.org/ebooks/155" className="text-loudBlue hover:underline">Edition 155</a> is the linked source. Treat this as a different commitment from a single Holmes story, even though both sit on a mystery shelf.</p></QuestionSection>
      <QuestionSection question="What if you want a book to return to for weeks?"><p>Alexandre Dumas and Auguste Maquet’s <Link href="/listen/the-count-of-monte-cristo" className="text-loudBlue hover:underline">The Count of Monte Cristo</Link> has a catalogue estimate of about fifty-two hours. <a href="https://www.gutenberg.org/ebooks/1184" className="text-loudBlue hover:underline">Gutenberg edition 1184</a> identifies the English text used by this listing. Check which translation you want before starting another version.</p><p>Leo Tolstoy’s <Link href="/listen/war-and-peace" className="text-loudBlue hover:underline">War and Peace</Link> is estimated at around sixty-two hours in our catalogue. <a href="https://www.gutenberg.org/ebooks/2600" className="text-loudBlue hover:underline">Edition 2600</a> credits Aylmer and Louise Maude as translators. Keep names and chapter headings handy if you are returning after gaps; a modern translation may read differently and have different rights.</p></QuestionSection>
      <QuestionSection question="How should you choose without overthinking it?"><ol className="list-decimal pl-6 space-y-2"><li>Pick the length and kind of session you want this week.</li><li>Read or hear a small sample of the actual edition.</li><li>Check the source notice and local rights; do not infer them from the author’s age alone.</li><li>Prepare the ebook and voice or download a recording before travelling.</li><li>Continue only if you want more of that book.</li></ol><p>Browse more options on the <Link href="/listen" className="text-loudBlue hover:underline">curated classics shelf</Link>. For the territorial boundary, see <a href="https://www.gutenberg.org/policy/permission.html" className="text-loudBlue hover:underline">Gutenberg’s permissions guidance</a>; the <a href="https://www.gov.uk/government/publications/copyright-notice-duration-of-copyright-term/copyright-notice-duration-of-copyright-term" className="text-loudBlue hover:underline">UK IPO duration notice</a> explains why translations need attention too. <Link href="/" className="text-loudBlue hover:underline">LoudReader</Link> is one way to hear a supported ebook, alongside recorded editions you may prefer.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Find a title on the classics shelf" subline="Compare the edition and a voice sample before beginning." />
    </ArticleLayout>
  );
}
