import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FREE_TIER } from "@/components/money/site";
import { FAQS } from "./content";
import meta from "./meta.json";
export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>Reading a book in English becomes more manageable when you choose material you can follow and decide in advance what to do with unfamiliar words. Start with a sample page. Can you explain what happened, even if some details are unclear? If not, try a simpler text, a familiar story or a graded reader. Use a dictionary for words that block meaning or recur usefully, and treat narration as optional support. This guide focuses on selecting books and maintaining understanding; you do not need to hit a fixed vocabulary percentage or finish a difficult classic to make the reading worthwhile.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Sample a passage, check its meaning and decide which words deserve a closer look." />
<QuestionSection question="How can you judge a book’s difficulty?"><p>Read a page from the middle as well as the opening. Then explain the situation in your own words: who is involved, what changed and what question the passage leaves you with. Notice whether unfamiliar vocabulary, sentence structure or assumed background knowledge is the main difficulty.</p><p>Vocabulary coverage matters, but a universal pass mark would be misleading. <a href="https://nflrc.hawaii.edu/rfl/item/43" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">Hu and Nation’s 2000 study</a> estimated roughly 98% coverage for adequate understanding of its fiction passage; that percentage was inferred, not a rule tested across all books. A <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/lang.12622" target="_blank" rel="noopener noreferrer" className="text-loudBlue hover:underline">2023 registered replication</a> did not reproduce 98% as a sufficient threshold. Use an actual comprehension check rather than counting six unfamiliar words and declaring a page suitable.</p><p>If a sample is too difficult, changing the edition or book is a useful choice. There is no requirement to struggle through the unabridged version first.</p></QuestionSection>
<QuestionSection question="Which unfamiliar words deserve a lookup?"><p>For reading for pleasure, try three categories. These are flexible habits, not rules for an exam or a technical instruction:</p><ul className="list-disc pl-6 space-y-2"><li><strong>Meaning blockers.</strong> Look up a word now if misunderstanding it changes the event or argument.</li><li><strong>Useful repeaters.</strong> Mark a recurring phrase and check it at the end of the paragraph or scene. Record an example, not just an isolated translation.</li><li><strong>Background detail.</strong> If you can follow the passage without it, continue and decide later whether it deserves attention.</li></ul><p>Do not assume context will always reveal the correct meaning. Return to uncertain words when precision matters, and check the whole phrase if a familiar word appears to mean something unexpected.</p></QuestionSection>
<QuestionSection question="When does listening alongside the text help?"><p>It can be useful when the written form is familiar but you cannot recognise the spoken phrase, or when a steady narration pace suits the passage. Keep the freedom to pause. Continuing to hear words while you have lost the meaning does not solve the problem.</p><p><Link href="/" className="text-loudBlue hover:underline">LoudReader</Link> shows word-following highlighting and supports sentence replay for imported books. Its voices are synthetic and can mispronounce a name or context-sensitive word, so check doubtful pronunciation elsewhere. Use text alone when audio adds more difficulty than it removes.</p><p>Speed control from 0.3x to 3.0x is Premium; notes, highlights and normal-speed narration are available on the free tier. {FREE_TIER.full}</p></QuestionSection>
<QuestionSection question="How do you make a long book manageable?"><ul className="list-disc pl-6 space-y-2"><li><strong>Use a natural stopping point.</strong> A scene, short section or chapter gives you something complete to describe afterwards.</li><li><strong>Keep a brief reminder.</strong> Write the main event or argument and any unanswered question before closing the book.</li><li><strong>Choose interest as well as level.</strong> A topic you know can supply helpful context; a book you dislike may not repay the effort.</li><li><strong>Try related material.</strong> Another story by the same author may reuse vocabulary, but do not assume it will always be easier.</li><li><strong>Change course when needed.</strong> A shorter book, a graded version or an entirely different subject can be a better next step.</li></ul><p>A small regular session is a practical option. There is no fixed number of minutes that guarantees you will finish within two weeks. Let the length and difficulty of the book shape your plan.</p></QuestionSection>
<QuestionSection question="Are classics a good place to begin?"><p>Some are, but “written for children” and “easy for a language learner” are different labels. Older prose may contain unfamiliar objects, social customs, dialect and humour. A modern graded reader can be more suitable than an unabridged classic.</p><p>The <Link href="/blog/easy-english-books-to-listen-to" className="text-loudBlue hover:underline">English book shortlist</Link> identifies useful starting points and specific difficulties. Its Project Gutenberg links refer to particular editions, whose availability depends on your location. For a book you already own, the <Link href="/turn-any-book-into-an-audiobook" className="text-loudBlue hover:underline">import guide</Link> explains supported DRM-free files.</p><p>LoudReader runs on iPhone and iPad, and compatible Apple Silicon Macs can use its iPad build. Local narration lets you prepare a book for offline reading and listening; it does not turn an unsuitable level into a suitable one.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Keep the text and narration together" subline="Use word highlighting and sentence replay when they help you follow your book." />
    </ArticleLayout>
  );
}
