import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FREE_TIER } from "@/components/money/site";
import { FAQS } from "./content";
import meta from "./meta.json";
export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>A useful student setup starts with the reading list, not playback speed. Separate prose you can follow by ear from material that needs diagrams, calculation or close comparison. Test each file before you depend on its narration, then leave time to write or answer questions. <Link href="/" className="text-loudBlue hover:underline">LoudReader</Link> reads supported DRM-free EPUBs and PDFs with word highlighting and offline speech after downloads. That can make a reading session more flexible, but the app does not promise faster learning or higher grades. Here is a workable way to organise assignments, handle awkward PDFs and keep track of what you still need to understand.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Read, listen, pause and return to the passage you need." />
<QuestionSection question="How should you sort a week of assigned reading?"><p>Make three small groups. Put narrative or explanatory prose in a listening list. Put papers with figures, mathematical work and difficult arguments in a read-with-the-source list. Keep assignments requiring answers or calculations in a separate work list: hearing an example is different from solving it.</p><p>Give each item a concrete finish line, such as summarising the author’s main claim or answering two seminar questions. “Play chapter four” is a playback task; “explain the difference between these theories” is a study task. The latter tells you when another pass is needed.</p></QuestionSection>
<QuestionSection question="How do you check a textbook PDF before listening?"><ol className="list-decimal pl-6 space-y-2"><li>Import a supported file you are allowed to use. A subscription or ebook purchase does not always provide a DRM-free download.</li><li>Compare the opening paragraphs with the original. Check two-column pages, footnotes, headings and page numbers for reading-order problems.</li><li>For a scanned PDF, check the local OCR output against the image. Small type, handwriting, poor scans and mathematical symbols can produce errors.</li><li>Sample a page from the middle as well as the introduction. A clean first page does not prove that later tables are readable.</li><li>Ask the library, publisher or accessibility service for a more suitable copy if essential content is missing.</li></ol><p>EPUB is often easier to follow when a book is mostly prose, because it is not tied to fixed page layout. Keep the original PDF available when page references matter. See <Link href="/turn-any-book-into-an-audiobook" className="text-loudBlue hover:underline">importing books for narration</Link> for the app workflow.</p></QuestionSection>
<QuestionSection question="How do you take notes without transcribing the audio?"><p>Before listening, put the assignment question at the top of your notes. Pause when a passage answers it and write a short claim, the supporting evidence and the source location. Put a question mark beside anything you cannot explain yet.</p><p>After a section, try a brief summary with the source hidden. Reopen it to check names, quotations and details. LoudReader includes notes and highlights on the free tier, and paper or a separate notes app works too. Avoid letting the availability of a highlight button decide what deserves a note.</p><p>For evidence and a sample session structure, see <Link href="/blog/is-text-to-speech-good-for-studying" className="text-loudBlue hover:underline">whether TTS is useful for studying</Link>.</p></QuestionSection>
<QuestionSection question="What is realistic to hear between classes?"><p>A familiar summary or a short passage is a reasonable starting point. LoudReader supports background playback and lock-screen controls, so you do not need to keep the reader visible. Download the book and required voice assets before going offline.</p><p>Save work that requires cross-referencing or written answers for somewhere you can stop. If you reach the destination and cannot say what the passage was about, replay a smaller section later or switch to reading. Time with headphones on is not automatically completed coursework.</p></QuestionSection>
<QuestionSection question="What if attention or accessibility is the main difficulty?"><p>Try one manageable passage with narration and visible text, then compare it with the format you normally use. Notice whether you follow the argument and can find your place after a pause. Adding sound helps some tasks and adds distraction to others; there is no universal student setting.</p><p>The <Link href="/blog/text-to-speech-adhd" className="text-loudBlue hover:underline">ADHD reading guide</Link> describes a practical trial without claiming treatment effects. For exams or formally assessed work, ask your institution which tools and formats are permitted. Do not assume that a general-purpose reading app is approved simply because it has speech.</p></QuestionSection>
<QuestionSection question="What should you know before choosing LoudReader?"><p>It runs on iPhone and iPad; compatible Apple Silicon Macs use the iPad build. Narration is local after downloads. This is a book-reading app, not a system screen reader or a service that explains diagrams.</p><p>{FREE_TIER.full} Speed control from 0.3x to 3.0x is a Premium feature; notes and highlights are free. Test a representative textbook page and the voice you intend to keep before making the app central to your routine.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Try a chapter in LoudReader" subline="Local narration and word highlighting. All voices free for the first 8 listening hours." />
    </ArticleLayout>
  );
}
