// LoudReader product facts refreshed against release_v1.12 on 2026-09-28.
// See docs/product-facts-2026-09-28.md. Older third-party check dates below remain unchanged.
// Local content constants for /private-text-to-speech-no-cloud.
// One page = one file pair (page.tsx + content.ts) + meta.json.
// See docs/money-page-contract.md for the contract.
//
// FACT PROVENANCE, checked on 2026-07-14:
//   - LoudReader claims verified against components/money/site.ts, the App
//     Store listing, app/faq/faq-data.ts and app/privacy in this repo
//     Superseded for diagnostics: shipping 1.12 includes Sentry and TelemetryDeck.
//     Local speech synthesis does not mean the entire app makes no requests.
//   - The "typical cloud TTS" column makes only definitional or hedged
//     claims: cloud synthesis by definition requires transmitting the text
//     to the provider's servers and an internet connection. "usually" and
//     "often" hedges cover account and quota practices without naming any
//     vendor. Specific vendor examples (word metering, sign-in) are on the
//     fact-checked /speechify-alternative-for-mac page, not restated here.
//   - Apple Spoken Content (mentioned as another private option):
//     https://support.apple.com/guide/mac-help/mh27448/mac. Built-in macOS
//     feature; speech is generated on the Mac.

import type { ComparisonRow } from "@/components/money/ComparisonTable";
import type { Faq } from "@/components/money/FaqSection";
import { FREE_TIER, PRIVACY, VOICES } from "@/components/money/site";

export const SLUG = "private-text-to-speech-no-cloud";

export const LAST_UPDATED = "2026-09-28";
export const FACTS_CHECKED_NOTE =
  "LoudReader 1.12 product facts checked September 28, 2026";

export const PAGE_TITLE = "Private Text to Speech: No Cloud, Fully On-Device";
export const PAGE_DESCRIPTION =
  "Learn how local text-to-speech avoids uploading books for narration, how to check offline capability, and why an app's other data flows still matter.";

export const H1 = "Private text to speech, with no cloud in the loop";

export const COMPARISON_COLUMNS = ["LoudReader (on-device)", "Typical cloud TTS service"];

export const COMPARISON_ROWS: ComparisonRow[] = [
  {
    label: "Where speech is generated",
    cells: [
      "On your Mac or iPhone, by a neural engine running locally",
      "On the provider's servers",
    ],
  },
  {
    label: "What leaves your device",
    cells: [
      "No book upload for narration; crash/performance diagnostics and usage analytics are sent",
      "Every sentence you listen to is transmitted for synthesis",
    ],
  },
  {
    label: "Works in airplane mode",
    cells: ["Yes, after content and voices are ready", "New cloud synthesis requires a connection; saved audio can play offline"],
  },
  {
    label: "Account required",
    cells: ["No, no sign-up at all", "Usually yes"],
  },
  {
    label: "Usage quotas",
    cells: [
      "No book-listening word quota; free article saving has a separate limit",
      "Often metered (words or characters per month)",
    ],
  },
  {
    label: "Voices & languages",
    cells: [
      `${VOICES.headline}. ${VOICES.availability}`,
      "Generally far more voices and languages, a real cloud advantage",
    ],
  },
  {
    label: "Hardware needed",
    cells: [
      "Apple Silicon Mac (macOS 15+) or iPhone/iPad (iOS 18+)",
      "Nearly anything with a browser",
    ],
  },
];

export const FAQS: Faq[] = [
  {
    q: "What does 'no cloud' text to speech actually mean?",
    a: "It means speech is generated by an engine on your device, without uploading the text for synthesis. That describes the speech path; an app can still make other network requests for downloads, purchases or analytics.",
  },
  {
    q: "How can I verify a TTS app is really on-device?",
    a: "After downloading the voice, disconnect and try text that has not already been rendered. This checks offline capability, but saved cloud audio can also play offline. Review the app architecture and privacy disclosures separately; airplane mode is not a privacy audit.",
  },
  {
    q: "Is LoudReader really private?",
    a: `Books are not uploaded for narration and no LoudReader account is required. ${PRIVACY.summary}`,
  },
  {
    q: "Can I use private text to speech for confidential work documents?",
    a: "Local narration avoids sending document text to a speech provider. It does not by itself establish compliance with an employer’s rules or professional confidentiality requirements. Review LoudReader’s diagnostics disclosures and your organisation’s policy before importing sensitive files.",
  },
  {
    q: "Does on-device text to speech sound robotic?",
    a: `Voice preference depends on the listener and material. LoudReader offers ${VOICES.headline}. ${VOICES.availability} ${FREE_TIER.full} Test your own passage before choosing a narrator.`,
  },
  {
    q: "What do I give up by avoiding cloud TTS?",
    a: "Breadth. Cloud services generally offer more voices and more languages — LoudReader covers 10 — and they run on any hardware, while LoudReader needs an Apple Silicon Mac or a recent iPhone. If those trade-offs matter more to you than privacy, a cloud service is the rational choice.",
  },
];
