// Local content constants for /private-text-to-speech-no-cloud.
// One page = one file pair (page.tsx + content.ts) + meta.json.
// See docs/money-page-contract.md for the contract.
//
// FACT PROVENANCE, checked on 2026-07-14:
//   - LoudReader claims verified against components/money/site.ts, the App
//     Store listing, app/faq/faq-data.ts and app/privacy in this repo
//     (on-device synthesis, no account, no personal data collection, only
//     network use = content downloads the user requests).
//   - The "typical cloud TTS" column makes only definitional or hedged
//     claims: cloud synthesis by definition requires transmitting the text
//     to the provider's servers and an internet connection. "usually" and
//     "often" hedges cover account and quota practices without naming any
//     vendor. Specific vendor examples (word metering, sign-in) are on the
//     fact-checked /speechify-alternative-for-mac page, not restated here.
//   - Apple Spoken Content (mentioned as another private option):
//     https://support.apple.com/guide/mac-help/mh27448/mac. Built-in macOS
//     feature; speech is generated on the Mac.

import type { ComparisonRow } from "@/components/money/ComparisonTable";
import type { Faq } from "@/components/money/FaqSection";

export const SLUG = "private-text-to-speech-no-cloud";

export const LAST_UPDATED = "2026-07-14";
export const FACTS_CHECKED_NOTE =
  "Product facts checked against the App Store listing and loudreader.io on July 14, 2026";

export const PAGE_TITLE = "Private Text to Speech: No Cloud, Fully On-Device";
export const PAGE_DESCRIPTION =
  "Private text to speech means the audio is generated on your own device, so your text is never uploaded. How to get it on Mac and iPhone, and how to verify an app is truly no-cloud.";

export const H1 = "Private text to speech, with no cloud in the loop";

export const COMPARISON_COLUMNS = ["LoudReader (on-device)", "Typical cloud TTS service"];

export const COMPARISON_ROWS: ComparisonRow[] = [
  {
    label: "Where speech is generated",
    cells: [
      "On your Mac or iPhone, by a neural engine running locally",
      "On the provider's servers",
    ],
  },
  {
    label: "What leaves your device",
    cells: [
      "Nothing, your library never leaves your device",
      "Every sentence you listen to is transmitted for synthesis",
    ],
  },
  {
    label: "Works in airplane mode",
    cells: ["Yes, the definitive test", "No, synthesis requires a connection"],
  },
  {
    label: "Account required",
    cells: ["No, no sign-up at all", "Usually yes"],
  },
  {
    label: "Usage quotas",
    cells: [
      "None, because nothing runs on someone else's servers to meter",
      "Often metered (words or characters per month)",
    ],
  },
  {
    label: "Voices & languages",
    cells: [
      "8 natural offline voices, English only for now",
      "Generally far more voices and languages, a real cloud advantage",
    ],
  },
  {
    label: "Hardware needed",
    cells: [
      "Apple Silicon Mac (macOS 15+) or iPhone/iPad (iOS 18+)",
      "Nearly anything with a browser",
    ],
  },
];

export const FAQS: Faq[] = [
  {
    q: "What does 'no cloud' text to speech actually mean?",
    a: "It means the speech audio is generated by an engine running on your own device, so the text never has to travel to a server. A cloud TTS service has to receive your text to synthesize it. A no-cloud app never sends it anywhere.",
  },
  {
    q: "How can I verify a TTS app is really on-device?",
    a: "Turn on airplane mode and press play. If narration keeps working with no connection, synthesis is happening on your device. LoudReader passes this test on both Mac and iPhone. The only features that need internet are the free-book catalog and article downloads you ask for.",
  },
  {
    q: "Is LoudReader really private?",
    a: "Yes. LoudReader is fully on-device and private, your library never leaves your device. It collects no personal data, requires no account, and your books, notes, highlights, and reading progress stay on your Mac or iPhone.",
  },
  {
    q: "Can I use private text to speech for confidential work documents?",
    a: "That's the main reason it exists. Contracts, medical records, legal briefs, client files, unpublished manuscripts: with on-device TTS they're read aloud without being uploaded to any third party. With a cloud service, listening to a document means transmitting it.",
  },
  {
    q: "Does on-device text to speech sound robotic?",
    a: "Not anymore. LoudReader runs a modern neural TTS engine with 8 natural offline voices, and every voice is free to try for your first 8 hours, so you can judge with your own ears before paying anything.",
  },
  {
    q: "What do I give up by avoiding cloud TTS?",
    a: "Breadth. Cloud services generally offer more voices and languages (LoudReader is English-only for now) and run on any hardware, while LoudReader needs an Apple Silicon Mac or a recent iPhone. If those trade-offs matter more to you than privacy, a cloud service is the rational choice.",
  },
];
