import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FREE_TIER } from "@/components/money/site";
import { FAQS } from "./content";
import meta from "./meta.json";
export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>Text to speech gives English learners a spoken version of text they choose. Use it for a specific exercise: check a phrase you did not catch, repeat a sentence, revisit useful vocabulary or hear your own writing. It does not explain a word’s meaning, assess your accent or guarantee that every pronunciation is correct. The four exercises below are suggestions you can adapt to your level. <Link href="/" className="text-loudBlue hover:underline">LoudReader</Link> supplies narration, word highlighting and sentence replay for supported material; keep a dictionary recording, teacher or other reliable language reference available when you need to verify the sound or meaning.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Choose a specific exercise and check what the narration helped you notice." />
<QuestionSection question="Exercise one: what did you actually hear?"><p>Choose a short, understandable passage. Listen once with the text hidden and write a few words or a brief summary of what you heard. Reveal the text and compare. Was the problem an unknown word, a familiar phrase you did not recognise in speech or a sentence you could hear but did not understand?</p><p>Replay only the relevant section while looking at the text. Word highlighting can help locate the spoken phrase. Then try it once more without the text if that fits your goal. This is an exercise for finding gaps, not a scored test or proof of a particular proficiency level.</p></QuestionSection>
<QuestionSection question="Exercise two: listen, pause and repeat a sentence"><p>Pick a short sentence whose meaning you know. Listen, pause and repeat it aloud. Compare the phrasing and stressed words you intended to say. If you record yourself, use that recording to notice a specific difference rather than trying to imitate the narrator’s entire voice.</p><p>This pause-and-repeat exercise is different from strict shadowing, where you speak along with or just behind the audio. Start with whichever is manageable. For more practice ideas, see <Link href="/blog/english-shadowing-practice" className="text-loudBlue hover:underline">English shadowing practice</Link>.</p><p>TTS can get names, abbreviations and context-dependent pronunciation wrong. Do not drill a doubtful example repeatedly: check a dictionary recording or ask a knowledgeable speaker first. Use human recordings as well when your goal is everyday conversation or a particular accent.</p></QuestionSection>
<QuestionSection question="Exercise three: keep a small phrase list"><p>Choose a few phrases from your reading that you would like to understand or use again. Write the phrase, what it means in that passage and your own example sentence. At a later session, hide the explanation and try to supply it before checking.</p><p>A word in a familiar paragraph is easier to recognise than to use independently. Try it in a different sentence rather than counting repeated playback as mastery. Notes and highlights in LoudReader are free, or you can keep the list in a notebook. For choosing manageable material, use the <Link href="/blog/easy-english-books-to-listen-to" className="text-loudBlue hover:underline">English book shortlist</Link>.</p></QuestionSection>
<QuestionSection question="Exercise four: hear your own writing"><p>Listen to a short paragraph you have written, using a supported import or saved-text workflow. Mark sentences that sound repetitive, unusually long or hard to follow. Then read the original and decide what needs changing.</p><p>The narrator does not correct grammar. It may read an incorrect sentence smoothly or make a correct name sound odd. Use it to notice possible problems, then check them with the grammar or writing resources you normally trust. It is a review pass, not an automatic proofreader.</p></QuestionSection>
<QuestionSection question="Which voice and speed should you use?"><p>Choose the clearest available voice for the text, rather than assuming a particular sound is best for every learner. Try normal speed first; pause when needed. If you have speed control, make small adjustments and listen again at the original pace occasionally when practising recognition at that pace.</p><p>LoudReader Premium provides 0.3x to 3.0x speed control. The app has 23 studio narrators across 10 languages, with availability depending on the device. {FREE_TIER.full} Non-English narration reads the source language; it does not translate a passage into English.</p></QuestionSection>
<QuestionSection question="How do these exercises fit into a wider routine?"><p>Pick one exercise for a short session rather than doing all four every day. Combine book practice with actual conversation, writing or the tasks your course asks you to do. For exam preparation, use official practice material and the required test conditions; this guide promises no score improvement.</p><p>LoudReader runs on iPhone and iPad, and on compatible Apple Silicon Macs as an iPad app. Speech is generated locally after necessary resources are available, so you can prepare material for offline sessions. The <Link href="/blog/learn-english-by-listening-to-books" className="text-loudBlue hover:underline">book-listening routine</Link> covers building a reading habit, while <Link href="/blog/reading-english-books-non-native" className="text-loudBlue hover:underline">the non-native reading guide</Link> focuses on book choice and dictionary use.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Practise with a passage you choose" subline="Word highlighting, sentence replay and free notes. Keep a language reference nearby for uncertain words." />
    </ArticleLayout>
  );
}
