import Link from "next/link";
import ArticleIllustration from "@/components/blog/ArticleIllustration";
import ArticleLayout from "@/components/blog/ArticleLayout";
import { articleMetadata } from "@/components/blog/articles";
import FaqSection from "@/components/money/FaqSection";
import QuestionSection from "@/components/money/QuestionSection";
import StoreCta from "@/components/money/StoreCta";
import Tldr from "@/components/money/Tldr";
import { FAQS } from "./content";
import meta from "./meta.json";

export const metadata = articleMetadata(meta);

export default function Article() {
  return (
    <ArticleLayout meta={meta}>
      <Tldr><p>Text to speech can provide an additional pass through a brief, statement or draft, but it cannot verify legal meaning, authorities or the accuracy of a document. Before importing client material, have the complete workflow approved under your firm’s policies. Local speech reduces the need to send text to a narration service; it does not by itself establish confidentiality, privilege or regulatory compliance. LoudReader is a general reader with local speech, diagnostics and usage analytics, not a certified legal document system.</p></Tldr>
      <ArticleIllustration variant="book-to-audio" caption="Treat narration as an additional pass, with the source document still authoritative." />
      <QuestionSection question="What needs approval before client material is imported?"><p>Check the app, device, source system, exported copy, backups and deletion process together. An approved document-management system does not automatically authorise exporting a file into another app. Ask the responsible person at your firm about the actual material and use.</p><p>For solicitors regulated in England and Wales, the SRA’s <a href="https://www.sra.org.uk/solicitors/guidance/confidentiality-client-information/" className="text-loudBlue hover:underline">confidentiality guidance</a> discusses protecting client information and assessing outsourcing arrangements. Other jurisdictions have their own requirements. This guide cannot approve a particular workflow or decide whether consent is needed.</p></QuestionSection>
      <QuestionSection question="What does on-device narration establish?"><p>It establishes where speech is generated. LoudReader does not upload a book to a speech server for narration, and its OCR runs locally. Speech is generated on device. That does not mean the whole app is network-free: LoudReader uses Sentry crash diagnostics and TelemetryDeck analytics. File transfers, device backups and any services you use before importing are separate parts of the workflow. In shipping version 1.12, usage analytics is on by default and there is no in-app switch to disable it.</p><p>No independent network or compliance audit is claimed here. Read the <Link href="/privacy" className="text-loudBlue hover:underline">privacy information</Link> and have the application reviewed before using confidential material. Test with a public or synthetic document while that decision is pending.</p></QuestionSection>
      <QuestionSection question="Which documents can benefit from an audio pass?"><p>Narrative sections of a statement or a draft argument may be worth hearing for flow and repetition. Keep the source visible when wording, a qualification or a defined term matters. Audio is less convenient for schedules, tables, redlines and dense cross-references.</p><p>Do not use a smooth reading as evidence that a clause is correct or a witness is consistent. Narration reads the extracted text; it does not perform legal analysis or check an authority.</p></QuestionSection>
      <QuestionSection question="How should you check a PDF before listening?"><ol className="list-decimal pl-6 space-y-2"><li>Use an approved copy of the correct document version.</li><li>Compare extracted text with a representative page, including footnotes and headers.</li><li>Check names, dates, amounts, negatives and defined terms against the original.</li><li>For a scan, inspect the OCR output; recognition can change consequential details.</li><li>Keep official page numbers and citations tied to the original document, not to the audio position.</li></ol><p>LoudReader can attempt on-device OCR for scans, but complex layouts and poor images remain limitations. Its <Link href="/listen-to-pdf-iphone" className="text-loudBlue hover:underline">PDF listening workflow</Link> is general reading guidance, not a legal review standard.</p></QuestionSection>
      <QuestionSection question="How do you manage the listening copy?"><p>If approved, record which version was imported and where local copies were created. Keep edits in the authoritative document. Follow the firm’s retention and deletion instructions for exports, downloads and backups; deleting an entry from a reader is not proof that every copy has been removed.</p><p>Avoid playing client material where others can overhear it. LoudReader runs on iPhone and iPad; its iPad build also runs on compatible Apple Silicon Macs. Device compatibility is separate from whether a work device permits the app.</p></QuestionSection>
      <QuestionSection question="What remains a visual and professional review?"><p>Citation accuracy, tracked changes, signatures, layout, authorities and the effect of precise wording still need the appropriate review. Use audio to add another perspective, then return to the actual text for decisions. The <Link href="/blog/proofread-by-listening" className="text-loudBlue hover:underline">proofreading guide</Link> describes a general revision loop without claiming legal verification.</p></QuestionSection>
      <FaqSection faqs={FAQS} />
      <StoreCta headline="Evaluate the workflow with a public document" subline="Have the app and handling process approved before importing client material." />
    </ArticleLayout>
  );
}
